### ISSUE TITLE
"blank-python" aws example may contain incorrect template.yml

### ISSUE THREAD

**Issue by Yuriy-Leonov** [awsdocs/aws-lambda-developer-guide#191]
Going through [this example](https://github.com/awsdocs/aws-lambda-developer-guide/tree/master/sample-apps/blank-python) I've stopped on [Deploy](https://github.com/awsdocs/aws-lambda-developer-guide/tree/master/sample-apps/blank-python#deploy) step. Following exection from aws is returned after `3-deploy.sh` execution:

> Uploading to c1badd00616f4d13770cb5a1b6d9dfc8  1169 / 1169.0  (100.00%)
> Successfully packaged artifacts and wrote output template to file out.yml.
> Execute the following command to deploy the packaged template
> aws cloudformation deploy --template-file /<path>/aws-lambda-developer-guide/sample-apps/blank-python/out.yml --stack-name <YOUR STACK NAME>
> 
> Waiting for changeset to be created..
> 
> Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [libsec98e4a2a4] is invalid. 'ContentUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter.

`out.yml` contains:
```
AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Properties:
      CodeUri: s3://lambda-artifacts-26c3674062aa40ab/c1badd00616f4d13770cb5a1b6d9dfc8
      Description: Call the AWS Lambda API
      Handler: lambda_function.lambda_handler
      Layers:
      - Ref: libs
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      Runtime: python3.8
      Timeout: 10
      Tracing: Active
    Type: AWS::Serverless::Function
  libs:
    Properties:
      CompatibleRuntimes:
      - python3.8
      ContentUri: package/.
      Description: Dependencies for the blank-python sample app.
      LayerName: blank-python-lib
    Type: AWS::Serverless::LayerVersion
Transform: AWS::Serverless-2016-10-31
```

`template.yml` contains(native from repository):
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Call the AWS Lambda API
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blank-python-lib
      Description: Dependencies for the blank-python sample app.
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.8
```

`bucket-name.txt` file, which was created on step with `./1-create-bucket.sh` contains: `lambda-artifacts-26c3674062aa40ab`. Correcponding bucket was created on S3 service with script above.
