### ISSUE TITLE
Layer documentation AWS cloudformation content example is wrong

### ISSUE THREAD

**Issue by AndrejMitrovic** [awsdocs/aws-lambda-developer-guide#399]
https://github.com/awsdocs/aws-lambda-developer-guide/blob/cad20e9f298fa16edfe0fb643ab8118b0fe2dc54/doc_source/configuration-layers.md#using-aws-cloudformation-with-layers

Specifies:

```
  libs:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: blank-nodejs-lib
      Description: Dependencies for the blank sample app.
      Content:
        S3Bucket: my-bucket-region-123456789012
        S3Key: layer.zip
      CompatibleRuntimes:
        - nodejs12.x
```

But `Content` should really be `ContentUri` and the `S3` prefix should be removed:

```
  libs:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: blank-nodejs-lib
      Description: Dependencies for the blank sample app.
      ContentUri:
        Bucket: my-bucket-region-123456789012
        Key: layer.zip
      CompatibleRuntimes:
        - nodejs12.x
```

As specified by these pages:
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-layerversion.html#sam-layerversion-contenturi
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-layerversion-layercontent.html

There seems to be a second page describing how to use layers, and it's more correct:
https://docs.aws.amazon.com/lambda/latest/dg/invocation-layers.html
